apiVersion: integration/v1
kind: Step
name: channel-create
tags:
  - collaboration
  - messaging
  - alerts
  - alerting
version: 1
summary: Create a Slack channel
description: |
  This step creates a Slack channel and invites a user.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/slack-step-channel-create
examples:
- summary: Create a new Slack room
  content:
    apiVersion: v1
    kind: Step
    name: create-channel
    image: relaysh/slack-step-channel-create
    spec:
      connection: !Connection { type: slack, name: my-slack-account}
      channel: !Parameter channel-name # Example: "relay-notifications"
      topic: !Parameter channel-topic # Example: "Notifications for Relay workflows"
      memberID: !Parameter memberID # Example: "UDHPDS88Z"
schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    $schema: 'http://json-schema.org/draft-07/schema#'
    type: object
    properties:
      channelID:
        type: string
    required: [channelID]
